# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    npm i
    cd examples/mochawesome-flags
    npm i
    npm test
  displayName: 'Run a multi-line script'

- task: PublishGenericHtmlReport@1
  inputs:
    tabName: 'E2E Dev'
    reportDir: 'examples/mochawesome-flags/test-report/index.html'
  condition: always()
- task: PublishGenericHtmlReport@1
  inputs:
    tabName: 'E2E QA'
    reportDir: 'examples/mochawesome-flags/test-report/index.html'
  condition: always()
- task: PublishGenericHtmlReport@1
  inputs:
    tabName: 'E2E NonProd'
    reportDir: 'examples/mochawesome-flags/test-report/index.html'
  condition: always()