# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    npm i
    cd examples/mochawesome-flags
    npm i
    npm test
  displayName: 'Run a multi-line script'

- task: JakubRumpca.azure-pipelines-html-report.PublishHtmlReport.PublishHtmlReport@1
  inputs:
    reportDir: 'examples/mochawesome-flags/test-report/index.html'
  condition: always()

